### PR TITLE
CS-35 add graph cms for tours

### PR DESCRIPTION
**Pull request by lpassamano**
## Description
Set up GraphCMS/Hygraph CMS for the tours and eye-spy scavenger hunts. Some new env vars were added for the integration, you can find the updated .env file in LastPass! I also added two tours to the CMS for QA purposes, `/tour/bloom` and `/eye-spy/aug-2022`.

## Jira
https://barnesfoundation.atlassian.net/browse/CS-35

### CODE REVIEW

**Comment by matthewsduff** [comment]
Kept running into a brick wall getting this repo up an running locally but nothing is jumping out at me from looking at the code

**Review by matthewsduff — APPROVED** [review]
Kept running into a brick wall getting this repo up an running locally but nothing is jumping out at me from looking at the code

**Comment by lpassamano** [comment]
> Kept running into a brick wall getting this repo up an running locally but nothing is jumping out at me from looking at the code

@matthewsduff Sorry about that! Let me know if you want to pair on setting this up and then I can fix the install documentation, since I know that there are probably some steps missing.

**Comment by matthewsduff** [comment]
> > Kept running into a brick wall getting this repo up an running locally but nothing is jumping out at me from looking at the code
> 
> @matthewsduff Sorry about that! Let me know if you want to pair on setting this up and then I can fix the install documentation, since I know that there are probably some steps missing.

Once I wrap up a cleaner version of the multi image PR I will circle back to this and document what exactly I'm running into

**Comment by matthewsduff** [comment]
Got it running locally, is there a particular part of the app I should check? Or is the fact that it is running good to go?

**Comment by lpassamano** [comment]
> Got it running locally, is there a particular part of the app I should check? Or is the fact that it is running good to go?

Awesome! I added two tours through the CMS that you can use for QA: `/tour/bloom` and `/eye-spy/aug-2022`

**Comment by matthewsduff** [comment]
Cool all looks good to me!

**Pull request merged**
